# Generated by Django 3.2.9 on 2021-11-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historicalRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('BGN', 'Bulgarian Lev'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('GBP', 'British Pound'), ('HUF', 'Hungarian Forint'), ('PLN', 'Polish Zloty'), ('RON', 'Romanian Leu'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('ISK', 'Icelandic Krona'), ('NOK', 'Norwegian Krone'), ('HRK', 'Croatian Kuna'), ('RUB', 'Russian Ruble'), ('TRY', 'Turkish Lira'), ('AUD', 'Australian Dollar'), ('BRL', 'Brazilian Real'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('HKD', 'Hong Kong Dollar'), ('IDR', 'Indonesian Rupiah'), ('ILS', 'Israeli New Shekel'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('MXN', 'Mexican Peso'), ('MYR', 'Malaysian Ringgit'), ('NZD', 'New Zealand Dollar'), ('PHP', 'Philippine Piso'), ('SGD', 'Singapore Dollar'), ('THB', 'Thai Baht'), ('ZAR', 'South African Rand')], default=None, max_length=3)),
                ('usd', models.FloatField(default=None, max_length=30)),
                ('brl', models.FloatField(default=None, max_length=30)),
                ('eur', models.FloatField(default=None, max_length=30)),
                ('jpy', models.FloatField(default=None, max_length=30)),
            ],
        ),
    ]
